export { default as IcBackWhite } from "./IcBackWhite";
export { default as IcCancle } from "./IcCancle";
export { default as IcSearch } from "./IcSearch";
export { default as IcBack } from "./IcBack";
export { default as IcCart } from "./IcCart";
export { default as IcLogo } from "./IcLogo";
export { default as IcMenu } from "./IcMenu";
export { default as IcStar } from "./IcStar";
export { default as IcStarBlue } from "./IcStarBlue";
